# Generated by Django 4.1.7 on 2023-02-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_categories_table_alter_news_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.TextField(),
        ),
    ]
