# Generated by Django 4.1.7 on 2023-02-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(default='NEWS', max_length=100),
        ),
    ]
