# Generated by Django 4.1.7 on 2023-02-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('NEWS', 'News'), ('PAGE', 'Page'), ('CATFORUM', 'Catégorie Forum')], default='NEWS', max_length=100),
        ),
    ]
