# Generated by Django 4.1.7 on 2023-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
    ]
