# Generated by Django 4.1.7 on 2023-03-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='name',
            field=models.CharField(default='Maintenance en cours', max_length=255, verbose_name='Titre de la maintenance'),
            preserve_default=False,
        ),
    ]
