# Generated by Django 4.1.7 on 2023-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_informations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informations',
            name='name',
            field=models.CharField(default='Maintenance en cours', max_length=255, verbose_name='Titre de la maintenance'),
        ),
    ]
